<#assign className =clazz.getIOSClassName()>
<#assign classNameLower = className?uncap_first>
<#assign iOSSuperclassName = clazz.getIOSSuperclass().getIOSClassName()>

/*
* this file is generated by ModelClass ${clazz}
*/

<#list clazz.getIOSImportClasses() as importClazz>
#import "${importClazz.getIOSClassName()}.h"
</#list>


<#if clazz.getImportIOSSuperClassName()?? >
#import "${clazz.getImportIOSSuperClassName()}.h"
</#if>

#import <Foundation/Foundation.h>
@interface ${className}:${iOSSuperclassName}

<#list clazz.getIOSFields() as iosField >

    <#if iosField.isPrimitive4IOS()>
    @property(nonatomic, assign) ${iosField.getIOSType()} ${iosField.getFieldName()} ;
    <#else>
    @property(nonatomic, strong) ${iosField.getIOSType()} ${iosField.getFieldName()} ;
    </#if>


</#list>



@end