<#assign className =clazz.getIOSClassName()>
<#assign classNameLower = className?uncap_first>
<#assign iOSSuperclassName = clazz.getIOSSuperclass().getIOSClassName()>

/*
* this file is generated by ModelClass ${clazz}
*/

#import "${className}.h"

#import <Foundation/Foundation.h>
@implementation ${className}

-(NSString *) description{
    //return [self toJSONString];
}

@end